import os
import time
import argparse
import numpy as np
import tensorflow as tf
from tensorflow import keras

def parse_args():
    parser = argparse.ArgumentParser(description="Dynamic TinyML Quantization & Benchmarking Pipeline")
    parser.add_argument("--model-path", type=str, default=None, help="Path to custom saved Keras model (.h5 or .keras)")
    parser.add_argument("--output-dir", type=str, default=".", help="Directory to save generated output files")
    return parser.parse_args()

def get_or_create_model(model_path=None):
    if model_path and os.path.exists(model_path):
        print(f"[+] Loading custom pre-trained model from: {model_path}")
        model = keras.models.load_model(model_path)
    else:
        if model_path:
            print(f"[!] Warning: Model path '{model_path}' not found. Falling back to default baseline CNN.")
        print("[+] Building default CNN model (Input: 28x28x1)...")
        model = keras.Sequential([
            keras.layers.Input(shape=(28, 28, 1)),
            keras.layers.Conv2D(16, (3, 3), activation='relu'),
            keras.layers.MaxPooling2D((2, 2)),
            keras.layers.Conv2D(32, (3, 3), activation='relu'),
            keras.layers.Flatten(),
            keras.layers.Dense(64, activation='relu'),
            keras.layers.Dense(10, activation='softmax')
        ])
        model.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['sparse_categorical_accuracy'])
        
        x_train = np.random.rand(500, 28, 28, 1).astype(np.float32)
        y_train = np.random.randint(0, 10, size=(500,))
        model.fit(x_train, y_train, epochs=1, batch_size=32, verbose=0)
    
    return model

def generate_dynamic_dataset(model, num_samples=200):
    input_shape = model.input_shape
    if isinstance(input_shape, list):
        input_shape = input_shape[0]
        
    target_shape = tuple(num_samples if dim is None else dim for dim in input_shape)
    print(f"[+] Dynamically generated evaluation dataset with shape: {target_shape}")
    return np.random.rand(*target_shape).astype(np.float32)

def representative_dataset_gen(eval_data):
    for i in range(min(100, len(eval_data))):
        yield [np.expand_dims(eval_data[i], axis=0)]

def benchmark_tflite(model_path, eval_data):
    interpreter = tf.lite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()
    
    input_details = interpreter.get_input_details()
    times = []
    num_runs = min(100, len(eval_data))
    
    for i in range(num_runs):
        sample = np.expand_dims(eval_data[i], axis=0)
        
        if input_details[0]['dtype'] == np.int8:
            scale, zero_point = input_details[0]['quantization']
            if scale > 0:
                sample = np.clip((sample / scale + zero_point), -128, 127).astype(np.int8)
            else:
                sample = np.clip(sample, -128, 127).astype(np.int8)
            
        interpreter.set_tensor(input_details[0]['index'], sample)
        
        start = time.perf_counter()
        interpreter.invoke()
        end = time.perf_counter()
        times.append((end - start) * 1000.0)

    avg_latency_ms = float(np.mean(times))
    file_size_kb = os.path.getsize(model_path) / 1024.0
    
    tensor_details = interpreter.get_tensor_details()
    sram_bytes = sum(
        t.get('bytes', np.dtype(t['dtype']).itemsize * int(np.prod(t['shape'])))
        for t in tensor_details
    )
    sram_kb = sram_bytes / 1024.0

    return avg_latency_ms, file_size_kb, sram_kb, input_details[0]['shape']

def convert_to_c_header(tflite_path, header_path):
    with open(tflite_path, "rb") as f:
        bytes_data = f.read()
    
    with open(header_path, "w") as f:
        f.write("// Auto-generated by tinyml_pipeline.py\n")
        f.write("#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n")
        f.write(f"const unsigned int g_model_len = {len(bytes_data)};\n")
        f.write("const unsigned char g_model[] __attribute__((aligned(4))) = {\n  ")
        for i, b in enumerate(bytes_data):
            f.write(f"0x{b:02x}, ")
            if (i + 1) % 12 == 0:
                f.write("\n  ")
        f.write("\n};\n\n#endif // MODEL_DATA_H\n")

def main():
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)
    
    fp32_path = os.path.join(args.output_dir, "model_fp32.tflite")
    int8_path = os.path.join(args.output_dir, "model_int8.tflite")
    header_path = os.path.join(args.output_dir, "model_data.h")

    model = get_or_create_model(args.model_path)
    eval_data = generate_dynamic_dataset(model)

    print("[+] Exporting FP32 TFLite flatbuffer...")
    converter_fp32 = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_fp32 = converter_fp32.convert()
    with open(fp32_path, "wb") as f:
        f.write(tflite_fp32)

    print("[+] Executing Post-Training INT8 Quantization...")
    converter_int8 = tf.lite.TFLiteConverter.from_keras_model(model)
    converter_int8.optimizations = [tf.lite.Optimize.DEFAULT]
    converter_int8.representative_dataset = lambda: representative_dataset_gen(eval_data)
    converter_int8.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter_int8.inference_input_type = tf.int8
    converter_int8.inference_output_type = tf.int8
    
    tflite_int8 = converter_int8.convert()
    with open(int8_path, "wb") as f:
        f.write(tflite_int8)

    fp32_lat, fp32_size, fp32_sram, in_shape = benchmark_tflite(fp32_path, eval_data)
    int8_lat, int8_size, int8_sram, _ = benchmark_tflite(int8_path, eval_data)

    print("\n================ Hardware Trade-off Profiling Summary ================")
    print(f"Detected Model Input Tensor Shape: {list(in_shape)}")
    print("-" * 72)
    print(f"{'Metric':<25} | {'FP32 Baseline':<15} | {'INT8 Quantized':<15} | {'Reduction':<10}")
    print("-" * 72)
    print(f"{'Model Size (KB)':<25} | {fp32_size:<15.2f} | {int8_size:<15.2f} | {((1 - int8_size/fp32_size)*100):<9.1f}%")
    print(f"{'SRAM Footprint (KB)':<25} | {fp32_sram:<15.2f} | {int8_sram:<15.2f} | {((1 - int8_sram/fp32_sram)*100):<9.1f}%")
    print(f"{'Avg Latency (ms)':<25} | {fp32_lat:<15.3f} | {int8_lat:<15.3f} | {((1 - int8_lat/fp32_lat)*100):<9.1f}%")
    print("======================================================================\n")

    convert_to_c_header(int8_path, header_path)
    print(f"[+] Successfully exported C header array to: '{header_path}'")

if __name__ == "__main__":
    main()
